### ISSUE TITLE
[1.19.2 Alpha] Broken Recipes

### ISSUE THREAD

**Issue by HalcyonSeas73** [sa-shiro/Minecraft-Compressed-Blocks#18]
**Mod Version**: 1.1.0.20220927
**forge Version**: 43.1.29

**Describe the bug**
The recipe to create ~~Compressed Crimson Nylium~~ _all the first tier Compressed Blocks_, which should be 3x3 of ~~Crimson Nylium~~ each respective block, does not exist. Instead, it creates itself (see screenshots, with Crimson Nylium as an example).

**How did it happen?**
What did you do that the bug / error / crash happened?
Tried to create the first tier of Compressed Crimson Nylium.

**Screenshots**
![image](https://user-images.githubusercontent.com/84727791/192640087-e142ccb5-a356-4b1d-b055-f86898173574.png)
![image](https://user-images.githubusercontent.com/84727791/192640144-26f62dfe-67e9-4906-bbd5-8a9fa68a05a6.png)

**Comment by sa-shiro** [comment]
Does this apply to every recipe of the first compression?

Unfortunately I can't check & fix this until tomorrow

**Comment by HalcyonSeas73** [comment]
The item crates seem to work (compressed bread, compressed apple etc), but the blocks don't appear to.
