### ISSUE TITLE
1.15.2(forge-31.1.14) crash server on load up[Caused by: net.minecraftforge.fml.ModLoadingException: compressedblocks has class loading errors ยง7net/minecraft/client/renderer/RenderType]

### ISSUE THREAD

**Issue by SDUBZ** [sa-shiro/Minecraft-Compressed-Blocks#2]
forge:
forge-31.1.14
cb:
compressedblocks-1.15.2-2.2.2
crash:
[crash-2020-02-21_21.05.14-server.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/4235598/crash-2020-02-21_21.05.14-server.txt)

**Comment by sa-shiro** [comment]
Could you provide more details about how it happened?

Like which action you performed,
Which block, when breaking, placing, crafting etc?

It seems it's either a problem with my `RenderTypeLookup` or an error from forge itself 

I'll have a look at it later, currently busy.

**Comment by sa-shiro** [comment]
> 
> 
> forge:
> forge-31.1.14
> cb:
> compressedblocks-1.15.2-2.2.2
> crash:
> [crash-2020-02-21_21.05.14-server.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/4235598/crash-2020-02-21_21.05.14-server.txt)

The issue is due to the updated Method of `RenderType`. in `31.1.14`

Not only did the mapping change (deobf -> obf) the function how it works has changed too, Update will come soon.
