### ISSUE TITLE
[FEEDBACK NEEDED] Adding new crate items

### ISSUE THREAD

**Issue by sa-shiro** [sa-shiro/Minecraft-Compressed-Blocks#23]
An upcoming update will feature a TON of new crate items and i need your feedback if you want all of them or of some of them should be removed, or if even some items should be removed from the crate items

<details><summary>complete list of all existing and planned crate items</summary>
<p>

- [x] PUMPKIN  
- [x] OAK_SAPLING  
- [x] SPRUCE_SAPLING
- [x] BIRCH_SAPLING
- [x] JUNGLE_SAPLING
- [x] ACACIA_SAPLING
- [x] DARK_OAK_SAPLING
- [x] MANGROVE_PROPAGULE
- [x] OAK_LEAVES
- [x] SPRUCE_LEAVES
- [x] BIRCH_LEAVES
- [x] JUNGLE_LEAVES
- [x] ACACIA_LEAVES
- [x] DARK_OAK_LEAVES
- [x] MANGROVE_LEAVES
- [x] AZAELA_LEAVES
- [x] FLOWERING_AZAELA_LEAVES
- [x] COBWEB
- [x] GRASS
- [x] FERN
- [x] AZAELA
- [x] DEAD_BUSH
- [x] SEAGRASS
- [x] SEA_PICKLE
- [x] DANDELION
- [x] POPPY
- [x] BLUE_ORCHID
- [x] ALLIUM
- [x] AZURE_BLUET
- [x] RED_TULIP
- [x] ORANGE_TULIP
- [x] WHITE_TULIP
- [x] PINK_TULIP
- [x] OXEYE_DAISY
- [x] CORNFLOWER
- [x] LILY_OF_THE_VALLEY
- [x] WITHER_ROSE
- [x] BROWN_MUSHROOM
- [x] RED_MUSHROOM
- [x] CRIMSON_FUNGUS
- [x] WARPED_FUNGUS
- [x] CRIMSON_ROOTS
- [x] WARPED_ROOTS
- [x] NETHER_SPROUTS
- [x] WEEPING_VINES
- [x] TWISTING_VINES
- [x] SUGAR_CANE
- [x] KELP
- [x] MOSS_CARPET

- [x] HANGING_ROOTS
- [x] BIG_DRIPLEAF
- [x] BAMBOO
- [x] TORCH
- [x] END_ROD
- [x] CHORUS_FRUIT
- [x] CHORUS_FLOWER
- [x] CACTUS
- [x] SOUL_TORCH
- [x] CHAIN

- [x] VINES
- [x] GLOW_LICHEN
- [x] LILY_PAD
- [x]  SKULK
- [x] SCULK_VEIN

- [x] WHITE_CARPET
- [x] ORANGE_CARPET
- [x] MAGENTA_CARPET
- [x] LIGHT_BLUE_CARPET
- [x] YELLOW_CARPET
- [x] LIME_CARPET
- [x] PINK_CARPET
- [x] GRAY_CARPET
- [x] LIGHT_GRAY_CARPET
- [x] CYAN_CARPET
- [x] PURPLE_CARPET
- [x] BLUE_CARPET
- [x] BROWN_CARPET
- [x] GREEN_CARPET
- [x] RED_CARPET
- [x] BLACK_CARPET
- [x] SUNFLOWER
- [x] LILAC
- [x] ROSE_BUSH
- [x] PEONY

- [x] LANTERN
- [x] SOUL_LANTERN

- [x] POINTED_DRIPSTONE  
- [x] REDSTONE_TORCH
- [x] REDSTONE_REPEATER
- [x] REDSTONE_COMPARATOR
- [x] PISTON
- [x] STICKY_PISTON
- [x] HOPPER

- [x] POWERED_RAIL
- [x] DETECTOR_RAIL
- [x] RAIL
- [x] ACTIVATOR_RAIL
- [x] MINECART

- [x] CHARCOAL

- [x] NETHER_QUARTZ
- [x] AMETHYST_SHARD

- [x] STICK

- [x] STRING
- [x] FEATHER
- [x] GUNPOWDER
- [x] WHEAT_SEEDS
- [x] WHEAT
- [x] FLINT
- [x] BUCKET
- [x] POWDER_SNOW_BUCKET
- [x] SNOWBALL
- [x] LEATHER
- [x] MILK_BUCKET

- [x] CLAY_BALL
- [x] PAPER
- [x] BOOK

- [x] EGG

- [x] INK_SACS
- [x] GLOW_INK_SACS
- [x] COCOA_BEANS
- [x] BONE_MEAL
- [x] BONE
- [x] SUGAR
- [x] PUMPKIN_SEEDS
- [x] MELON_SEEDS
- [x] ENDER_PEARL
- [x] BLAZE_ROD
- [x] NETHER_WART
- [x] ENDER_EYE

- [x] RABBIT_HIDE
- [x] BEETROOT_SEEDS

- [x] HONEYCOMB
- [x] APPLE
- [x] MUSHROOM_STEW
- [x] BREAD
- [x] RAW_PORKCHOP
- [x] COOKED_PORKCHOP
- [x] GOLDEN_APPLE
- [x] RAW_COD
- [x] RAW_SALMON
- [x] TROPICAL_FISH
- [x] PUFFERFISH
- [x] COOKED_COD
- [x] COOKED_SALMON
- [x] CAKE
- [x] COOKIE
- [x] MELON_SLICE
- [x] DRIED_KELP
- [x] RAW_BEEF
- [x] COOKED_BEEF
- [x] RAW_CHICKEN
- [x] COOKED_CHICKEN
- [x] ROTTEN_FLESH
- [x] SPIDER_EYE
- [x] CARROT
- [x] POTATO
- [x] BAKED_POTATO
- [x] POISONOUS_POTATO
- [x] PUMPKIN_PIE
- [x] RAW_RABBIT
- [x] COOKED_RABBIT
- [x] RABBIT_STEW
- [x] MUTTON
- [x] COOKED_MUTTON
- [x] BEETROOT
- [x] BEETROOT_SOUP
- [x] SWEET_BERRIES
- [x] GLOW_BERRIES
- [x] HONEY_BOTTLE
- [x] ARROW

- [x] GHAST_TEAR
- [x] WATER_BOTTLE
- [x] GLASS_BOTTLE
- [x] FERMENTED_SPIDER_EYE
- [x] BLAZE_POWDER
- [x] MAGMA_CREAM
</p>
</details>

**Comment by Baggytrousers27** [comment]
Pickles and sunflowers ... Perhaps beans [Raw iron/copper/gold] if you're feeling spicy.

**Comment by PurpleHel** [comment]
All the wools?

**Comment by HalcyonSeas73** [comment]
- All the logs?
- Log planks?
- Amethyst block?
- Honey block?

**Comment by PurpleHel** [comment]
Quartz blocks!!!!

**Comment by sa-shiro** [comment]
following will be added:

- [ ] Logs and variants
- [ ] Honey
- [ ] Amethyst 
- [ ] Wool (carped was planned anyways)
- [ ] (raw) Ore blocks and ingots (same as above)
- [ ] Flowers

# Should the crate items be a separate mod?

/polls "Yes" "No"

**Comment by sa-shiro** [comment]
unfortunately issues dont allow polls, id be thankful if you check this out and vote on it!
https://github.com/sa-shiro/Minecraft-Compressed-Blocks/discussions/26

**Comment by toffi3** [comment]
Will this update be released for 1.18 Fabric?

**Comment by sa-shiro** [comment]
> Will this update be released for 1.18 Fabric?

1.19 forge will have priority for now and will take some time, mainly because of the textures
after that a backport to 1.18, 1.17 and 1.16 will be done (thats easy, some items just have to be removed)

after that ill look how much changed on the fabric side, might be easy to port as well

**Comment by HalcyonSeas73** [comment]
- Podzol
- Glowstone (Block)
- Grass Block
- Glass Block
- Obsidian Block
- Snow Block

**Comment by sa-shiro** [comment]
> - Podzol
> - Glowstone (Block)
> - Grass Block
> - Glass Block
> - Obsidian Block
> - Snow Block

I didn't get grass block to work because of the texture and texture generation...

Obsidian and glass should be a compressed block already, if I don't remember it wrong 

Or do you want a crated version specifically?

**Comment by HalcyonSeas73** [comment]
> Or do you want a crated version specifically?

I've checked, Obsidian Block and Glass Block are not compressed; the only glass item compressed (into a crate) is Glass Bottle.

Can we also add Smooth Stone as a compressed block?

**Comment by sa-shiro** [comment]
Hmmm... obsidian should have been compressed as I gave them different strength and resistances...
Weird, I'll look into it!

Unfortunately I have some deadlines this week so I might not be able to work on it till Friday 🙁

**Comment by HalcyonSeas73** [comment]
- Melon (blocks); Pumpkin has compression, but Melon does not.

**Comment by HalcyonSeas73** [comment]
> Hmmm... obsidian should have been compressed as I gave them different strength and resistances...
> Weird, I'll look into it!

![image](https://user-images.githubusercontent.com/84727791/202851348-bbc95917-9298-4634-bf31-dca2dd032811.png)

**Comment by HalcyonSeas73** [comment]
@sa-shiro  Is there an update on the progress?

**Comment by sa-shiro** [comment]
@HalcyonSeas73 
>  Is there an update on the progress?

sorry fpr the late update...
I am currently trying to re-implement configurable compression (currently done with json as parts that code exists already in some way)
but i have to fix several issues with it, like properly generating resources on startup etc. also because its not registered as a real config, i might have to switch to toml later on

**Comment by HalcyonSeas73** [comment]
Now that the 1.19.4 update has been released, is there still progress being made on the additions to Compressed Blocks?

**Comment by sa-shiro** [comment]
> Now that the 1.19.4 update has been released, is there still progress being made on the additions to Compressed Blocks?

It is, I am currently working on updating and polishing up my mods which should be done by now.  

The next plan is to continue the work on this mod, but it might take a while as I will recreate the crate textures and downscale them, including the atlas files used for this which are quite big

**Comment by sa-shiro** [comment]
> Now that the 1.19.4 update has been released, is there still progress being made on the additions to Compressed Blocks?

quick update on the progress:
it might ***MAYBE*** take a bit longer than expected, as i have decided to change the dynamic way of adding crates to registering every crate item one by one (this also improves readability of the code and removes some unnecessary doubled code) 

However i try to complete the next update as fast as possible!

**Comment by sa-shiro** [comment]
a addition to this i forgot:
any items on this list / not on this list you want to see as a compressed / crate variant?

**Comment by HalcyonSeas73** [comment]
I can think of a few things; essentially just collating the list already in the thread here.

Crates:
- charcoal
- gunpowder
- pickles
- all the flowers
- perhaps ingots/nuggets?
- carpets

Blocks:
- Podzol
- Glowstone (Block)
- Grass Block
- Glass Block
- Obsidian Block
- Snow Block
- All the logs?
- Log planks?
- Amethyst block?
- Honey block?
- Raw Ore blocks
- Melon
- Quartz
- Wools

Mind you, that's before I add the list at the beginning of the thread you had wondered about.

**Comment by sa-shiro** [comment]
@HalcyonSeas73 
at first i wanna thank you for helping me with your feedback and suggestions!

i have a question for you, what do you think about this change? (ignore the texture for now)  
in the upcoming update you will need to craft a crate in order to crate items, this also eliminates potential recipe conflicts to say :D
![image](https://user-images.githubusercontent.com/7215049/234287579-c09d250c-8307-417a-90ad-005483329925.png)

**Comment by PurpleHel** [comment]
@sa-shiro I personally don't like that idea,tho the question wasn't directed at me. I use mods that automatically compress items if they can be compressed. (sophisticated backpacks&storage) Having to craft a crate would break that convenience. I have polymorph for avoiding recipe conflicts.

**Comment by sa-shiro** [comment]
ah okay, i will see what i can do then about recipe conflicts (like crated wheat)

**Comment by PurpleHel** [comment]
I don't know about everyone else, but things like wheat to hay bales that can already be easily combined and separated, I don't need in this mod. I just need this for things that can't be combined/compressed already, like hay bales.

**Comment by sa-shiro** [comment]
> 



> I don't know about everyone else, but things like wheat to hay bales that can already be easily combined and separated, I don't need in this mod. I just need this for things that can't be combined/compressed already, like hay bales.

yeah, i either just remove those or add an optional config setting to use an empty crate item with recipes to enable those conflicting ones like wheat

**Comment by HalcyonSeas73** [comment]
Yeah, agreed with PurpleHel, crating like that is not really something I'd like in the mod. I use [bdew's Compacter](https://www.curseforge.com/minecraft/mc-mods/compacter) for automated compression, as well as Storage Drawers' Compacting Drawers for long-term storage. I think having conflicting recipes is just going to be part of the mod; you never know what other mod is going to add conflicts. 

As for hay bales, the bales themselves could be crated (or blocks), as there's already a 3x3 recipe for wheat.

**Comment by sa-shiro** [comment]
@HalcyonSeas73 and @PurpleHel 

all items have been added by now, just the blocks are missing.
However id like to ask for your opinion about the current texture design

Should the textures remain as they are now or change them?
im not that good of an artist, but im working on a new texture atm, here is a preview of the new texture:
(left is ofc the old texture, but with no item in it)
![image](https://user-images.githubusercontent.com/7215049/234629098-6fbc4446-5789-4d23-a32a-d42135608512.png)

it is also planned to add numbers on top of the crate to distinguish between the level of crates

**Comment by PurpleHel** [comment]
The new texture idea doesn't really look like a crate to me, but it's definitely easier to see the contents. I often have trouble IDing the contents of crates when they're in inventory with the current texture, and have to hover over and read the name.

**Comment by sa-shiro** [comment]
i will keep the current texture design then, however i will fix the texture to make the content more clear and identifiable, thanks for your response!

**Comment by HalcyonSeas73** [comment]
I can see the new texture being cratelike, like a crate of oranges. it doesnt match the block vibe of minecraft all that well though; despite that, i still like it. If not the new design, maybe the old one could be 'simplified', colour-wise, to make the contents easier to identify? The numbers are also a good idea.

**Comment by sa-shiro** [comment]
actually the current texture had numbers on its side, however i really dont know what happened that i didnt add it to the final product lol 🤔

**Comment by HalcyonSeas73** [comment]
Might be a big ask, but adding forge tags to the crates/blocks? Like cb:double_compressed, cb:triple_compressed etc.

**Comment by sa-shiro** [comment]
> Might be a big ask, but adding forge tags to the crates/blocks? Like cb:double_compressed, cb:triple_compressed etc.
> 
> Tags make it easier for some mods' filters.

thats not as of a big task as you might think, i already use tags or at least minecraft almost forces you to use tags `MINEABLE_WITH_PICKAXE` etc. so yeah, i will add that

**Comment by sa-shiro** [comment]
update: everything is finished by now, howeer because of the amount of new items, the textures still take some time.. 
I hope i can finish it till the end of this week!

**Comment by sa-shiro** [comment]
Terrible update...

I'm sorry to share this with you, but unfortunately the update will be delayed even longer....

My MoBo just died today and I have to wait for a replacement 

I'm trying to work on my laptop to get the update done however, it's not the fastest :( actually its a terrible old office laptop 

I am really sorry for this and I hope you all can understand my situation.

**Comment by sa-shiro** [comment]
However, if you want a Alpha build of the current started, I can setup a build, but it won't have any textures for the crates, except the empty placeholder crate texture

**Comment by HalcyonSeas73** [comment]
> However, if you want a Alpha build of the current state, I can setup a build, but it won't have any textures for the crates, except the empty placeholder crate texture

Sure! And no worries about your mobo dying; it happens. An old office laptop is better than nothing!

Perhaps related, but the current 1.19.4 release still has a 'conflicting' recipe: the bonemeal->crate of bonemeal recipe is the same recipe in vanilla as bonemeal->bone block. Unsure if you continue to plan on removing conflicting recipes in the meanwhile.

**Comment by sa-shiro** [comment]
> > However, if you want a Alpha build of the current state, I can setup a build, but it won't have any textures for the crates, except the empty placeholder crate texture
> 
> Sure! And no worries about your mobo dying; it happens. An old office laptop is better than nothing!
> 
> Perhaps related, but the current 1.19.4 release still has a 'conflicting' recipe: the bonemeal->crate of bonemeal recipe is the same recipe in vanilla as bonemeal->bone block. Unsure if you continue to plan on removing conflicting recipes in the meanwhile. 

Thank you!

Oh, I didn't even know I added Bone meal to the latest available version 😅 I might have added it by accident

**Comment by sa-shiro** [comment]
@HalcyonSeas73 here is the current dev version, please also let me know if the tags work (`#single` ... `#c0`... and maybe even `#compression`)

be reminded that because of creative inventory changes in 1.19.3 that this version can not be made compatible with 1.19 - 1.19.2 and works only on 1.19.3 and 1.19.4

a version for other minecraft version will be released shortly after the initial release for 1.19.3/4
[compressedblocks_1.19.4-4965c3c-1.2.2-SNAPSHOT.zip](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/11413029/compressedblocks_1.19.4-4965c3c-1.2.2-SNAPSHOT.zip)

(you have to open and extract the archive, github doesnt allow uploading .jar files in comments)

**Comment by HalcyonSeas73** [comment]
Some feedback:
-Instead of removing crated bonemeal/bone blocks entirely, I would crate _just_ the bone blocks, as that's the end product of combining bone meal anyway, and it can be further reduced into bonemeal individually (reversible recipe); the same might go for wheat via hay bales (that is, having compressed hay bales), since youd just be leftover with some scraps of wheat.

- The text in JEI for carpets appears to say (amount) x Redstone (Colour) Carpet; in general, the JEI tooltip is different for the 'newly added' things vs the original/older things; the old tooltips list the amount in the format of X Blocks, whereas new items list it as Xx Item (with the exception to carpet, mentioned earlier)

- The tags don't appear to be 'populated' with their relevant blocks?

- None of the items under the 'Blocks' section seem to have been added yet, in addition to any (crated or otherwise) ingots or nuggets; it may be worth reconsidering adding nuggets/ingots of the first place, since their Block of X suits the purpose fairly well, relating to the first point of vanilla-crafting the final product.

**Comment by sa-shiro** [comment]
just as a reminder, its a early snapshot version, i dont have acces to the most recent project files until Wed when the new mobo arrives ^^

**Comment by sa-shiro** [comment]
everything almost finished
to note the problem with the tags:  `https://github.com/mezz/JustEnoughItems/issues/2814`  thats why (block) tags dont work, its not supported yet

however my workaround for this is that i just add them as item tags instead
![grafik](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/7215049/9644fe7f-9683-4bb6-9aef-20d8a03c60b0)

**Comment by HalcyonSeas73** [comment]
I hadn't been testing tags using JEI, I had been testing block tags via the Filter Card in RFToolsStorage. Item tags _might_ work...? 

I can test and see, once a new version with the item tags is released.

**Comment by sa-shiro** [comment]
addressed in https://github.com/sa-shiro/Minecraft-Compressed-Blocks/commit/d9d16cd25e7f8e4a6ae08809f7526c9bbda484bb
