### ISSUE TITLE
Suggestion: Do not crate Wheat - but do crate Hay Balls instead

### ISSUE THREAD

**Issue by Maxwelljones** [sa-shiro/Minecraft-Compressed-Blocks#27]
Hello,

It's probably interesting to compress Hay balls instead of wheat, so that you can still make Hay balls.
Hay balls are great decoration items, and still in use in some mods (minecolonies for example).

Thanks!

**Comment by sa-shiro** [comment]
There's no compressed hay ball block??

I might have forgotten this or removed it because of the rotational textures and forgot to add it back 🤔

**Comment by Maxwelljones** [comment]
There's a wheat compression in 1.19.2, and because of that you can't make hay balls.

**Expected:** 
![image](https://user-images.githubusercontent.com/3750700/195780293-86ef31eb-8a60-4a84-b1bd-aa74f88c1638.png)

**Getting:**
![image](https://user-images.githubusercontent.com/3750700/195780393-baf82b0b-7025-422e-adfb-5fa138c9e56d.png)

**Further** to answer your question, no there's no hay ball block:
![image](https://user-images.githubusercontent.com/3750700/195780567-41825e51-f3d0-4425-802d-88ddfb74079a.png)

Hope that's clarified?

**Comment by sa-shiro** [comment]
Does the recipe book let you decide which recipe to use?
Like if you click the hay ball recipe does it let you craft the hay ball instead of the crate?

I'll fix this, but because of some deadlines this week i might not be able to fix that until Friday

**Comment by Maxwelljones** [comment]
Sorry I was sure I did reply to your message. Seems I didnt.

On a crafting table, I cannot choose which recipe to use. I can only craft the crate.

Thank you for the workaround that works fine ;)
