### ISSUE TITLE
[1.19.2] Incorrect Triple Compressed Sand Recipe

### ISSUE THREAD

**Issue by HalcyonSeas73** [sa-shiro/Minecraft-Compressed-Blocks#29]
**Mod Version**: 1.1.0-20220930
**forge Version**: 43.1.52

**Describe the bug**
The recipe for Triple Compressed Sand is 9x Compressed Sand. 
The recipe for Double Compressed Sand is 9x Triple Compressed Sand.

I assume it's a bug?

![image](https://user-images.githubusercontent.com/84727791/202851289-503470f4-f3f2-4f48-a083-33e6e4371334.png)

**Comment by sa-shiro** [comment]
There was an Typo in the src that caused this. i sincerely apologize for this, will be fixed as soon as its pushed/uploaded to cf/modrinth
