### ISSUE TITLE
Crafting recipe for double compressed stone

### ISSUE THREAD

**Issue by Mrsuperx13** [sa-shiro/Minecraft-Compressed-Blocks#3]
**Mod Version**
compressedblocks-1.15.2-2.3.0.jar
**forge Version**
31.1.22

**Describe the bug**
There does not seem to be a crafting recipe for double compressed stone.

**How did it happen?**
I played the game.

**Screenshots**
https://imgur.com/a/qldTaSR
as you can see if JEI doesn't even show recipe

**Comment by sa-shiro** [comment]
Actually there is an recipe for it, but for whatever reason it doesn't get loaded...
I'll have a look at it tomorrow / later

**Comment by sa-shiro** [comment]
fixed with https://github.com/sa-shiro/Minecraft-Compressed-Blocks/commit/e977fe74cbb48d0b691a904951f5487605d7c381

"item" was set to "tag" idk why xD
