### ISSUE TITLE
[1.19.2] Broken Textures

### ISSUE THREAD

**Issue by HalcyonSeas73** [sa-shiro/Minecraft-Compressed-Blocks#30]
**Mod Version** 1.1.1
**forge Version** 43.1.52

**Describe the bug**
Some textures are broken with the latest update.

**Screenshots**
![image](https://user-images.githubusercontent.com/84727791/202863764-e40d8981-7881-481a-ab50-e1388e1fb2f8.png)

**Comment by sa-shiro** [comment]
this is already fixed in https://github.com/sa-shiro/Minecraft-Compressed-Blocks/commit/6dea9aed4936d8935164ea0b34425d8d57b6c837
upload to cf is under review

**Comment by sa-shiro** [comment]
take this as a faster solution, idk how long curseforge will need

https://github.com/sa-shiro/Minecraft-Compressed-Blocks/releases/tag/1.1.1
