### ISSUE TITLE
[1.19.2] Crash on startup

### ISSUE THREAD

**Issue by DelviousCrafts** [sa-shiro/Minecraft-Compressed-Blocks#32]
Compressed Blocks: c15be84-1.2.0
Forge: 43.2.8

**Describe the bug**
Game crashes during startup.

**How did it happen?**
Attempting to load the game

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/46658624/232180569-7577f92b-aa4f-4ca0-b674-4ca839e571d6.png)

[Crash Report](https://gist.github.com/DelviousCrafts/408f44dd214b5e7df694a739f338d527)
[Latest Log](https://gist.github.com/DelviousCrafts/24d1da22d821235bfc81cb576a3a3932)

**Comment by sa-shiro** [comment]
Ohh, it seems it's not compatible with 1.19.2, I'm sorry I will release a version that's compatible with the other versions!

Currently it might only be compatible with 1.19.4, it maybe works with 1.19.3 but just maybe
