### ISSUE TITLE
[1.19.4] 1.2.2 Bugs

### ISSUE THREAD

**Issue by HalcyonSeas73** [sa-shiro/Minecraft-Compressed-Blocks#33]
**Mod Version** 1.2.2
**forge Version** 45.0.64

**Describe the bug**
 - Many crates are named `item.compressedblocks.crated_end_rod` for example, and have no item texture, just the crate (as with SNAPSHOT)
 - the compressed blocks have tags of c0, the crates do not
 - A few missing items/blocks from suggested list:
      - Smooth stone
      - Amethyst block  
      - Podzol
      - Glowstone (Block)
      - Grass Block
      - Glass Block
      - Snow Block
      - Melon Block
      - Quartz Block

**How did it happen?**
Viewing items via JEI.

**Screenshots**
![image](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/84727791/52825718-994a-46bb-91de-c2c35806acf5)
![image](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/84727791/a595e2f8-5c4f-401d-91d4-95487e99e75a)

**Comment by sa-shiro** [comment]
The supplementation thing is not a issue related to Compressed Blocks itself 

It rather tries to create a sign variant of the newly added compressed Wood types, if there's a way to exclude blocks in supplementaties I'd recommend doing so.

It seems that assets didn't get commute correctly to GitHub, I'll fix this.

Also crates aren't meant to be placable, they are just items

**Comment by HalcyonSeas73** [comment]
I've updated the main post, removing that information.

**Comment by sa-shiro** [comment]
> I've updated the main post, removing that information.

Some time later I might look into what Supplementaries is doing, but that's not planned atm 

Also as you asked if the crates are placable...

I might be thinking about changing it from items to blocks, that way I don't have to create every texture by hand too which saves a lot of time

**Comment by HalcyonSeas73** [comment]
> Some time later I might look into what Supplementaries is doing, but that's not planned atm

Supplementaries, I suspect, is dynamically adding wood things based on woods in the game, to be compatible with other mods that add their own unique woods.

**Comment by sa-shiro** [comment]
addressed in https://github.com/sa-shiro/Minecraft-Compressed-Blocks/commit/d9d16cd25e7f8e4a6ae08809f7526c9bbda484bb
