### ISSUE TITLE
[Suggestion] 1.20.1 Port

### ISSUE THREAD

**Issue by HalcyonSeas73** [sa-shiro/Minecraft-Compressed-Blocks#34]
Not a bug, but a feature request; a port to 1.20.1? It's supposedly not too different to 1.19.4, as I've heard that "1.19.4 is basically a 1.20 snapshot".

**Comment by sa-shiro** [comment]
It kinda is, I actually wanted to add 1.20 items in the current version, but j seem to have forgotten about this

**Comment by sa-shiro** [comment]
Addressed with https://github.com/sa-shiro/Minecraft-Compressed-Blocks/commit/e28be9d121cf2a01adf23a73a02568b9250e7cc6
