### ISSUE TITLE
1.19.2 preventing stone from dropping

### ISSUE THREAD

**Issue by PurpleHel** [sa-shiro/Minecraft-Compressed-Blocks#36]
Compressed Blocks-forge-1.19-1.3.4.jar
forge 43.2.14

When mining stone or ores like coal or diamond, tool loses durability, experience drops, but stone/ore does not drop.

Problem not seen with previous version of mod.

Tested in a completely new world with only forge and compressed blocks.

**Comment by sa-shiro** [comment]
can you give more details?
vanilla or compressed blocks, if compressed -> which levels are affected?

**Comment by PurpleHel** [comment]
Vanilla blocks aren't dropping. Seen when breaking plain stone (should drop cobblestone, doesn't), coal ore, diamond ore, stone bricks, stone brick stairs. None of them dropped what they should have dropped, tho all took durability from the tool and dropped XP. Blocks like logs and leaves DID drop without issue.

**Comment by sa-shiro** [comment]
> Vanilla blocks aren't dropping. Seen when breaking plain stone (should drop cobblestone, doesn't), coal ore, diamond ore, stone bricks, stone brick stairs. None of them dropped what they should have dropped, tho all took durability from the tool and dropped XP. Blocks like logs and leaves DID drop without issue.

just been testing it right now, something is wrong with the assets, im fixing it right now by re-generating the assets for 1.19.2

**Comment by sa-shiro** [comment]
should be fixed now, at least as of my testings

**Comment by sa-shiro** [comment]
@PurpleHel curseforge will take a while as it needs verification / approval, you can get it instantly over modrinth, as soon as the build has finished

**Comment by PurpleHel** [comment]
It's about 5am here, I'm going to do tomorrowMe a favor and get some sleep, but I'll try the new build tomorrow probably. But if it's working for you, it's probably fine! Thank you!

**Comment by sa-shiro** [comment]
no problem and thanks for reporting!! have a great night and sleep :)

**Comment by PurpleHel** [comment]
Yup, it's fixed in 1.3.5! Thanks again!
