### ISSUE TITLE
Game Crashes 

### ISSUE THREAD

**Issue by Cats987** [sa-shiro/Minecraft-Compressed-Blocks#37]
**1.3.5**
**44.1.23**

**Game Crashes immediately since the new update**
Game just up and crashes as soon as I updated to the new version of the mod.

**Updating to the latest version**
Updated the mod.

**Screenshots**
No screenshots, but will provide logs.
[crash-2023-07-12_14.54.45-client.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/12031318/crash-2023-07-12_14.54.45-client.txt)

**Comment by sa-shiro** [comment]
Can you confirm that this happens in **1.19.4** too? as its build using **1.19.4** so there is **no gurantee** it works on 1.19.3 (and as of my testings 1.19.4 works as intended)

may i ask why you are using 1.19.3 at all tho? you probably shouldnt use 1.19.3 and upgrade to 1.19.4, most of your mods should exist for 1.19.4 as it introduced rather minor changes

**Comment by Cats987** [comment]
Unsure if it happens on 1.19.4 but I'm not trying to upgrade my game, that new update for the mod came up on the forge mod loader as 'for 1.19.3'. Not sure why

**Comment by sa-shiro** [comment]
You can try to use 1.3.4 or older if they work, if not i need to create a build for 1.19.3 specifically
there shouldnt be major differences between those versions anyways

**Comment by Cats987** [comment]
Will do, will also lyk if it continues to crash after downgrading

**Comment by Cats987** [comment]
Yes, now after downgrading it works. Unsure why, but it shows as a compatible update. 
![image](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/89990174/3e42f1c7-a613-4325-bddf-1d681d2fb3d7)

**Comment by sa-shiro** [comment]
I am currently working on unifying all versions in one project, however i started now to import a 1.19.3 versions so i can quickly release a build manually for 1.19.3 which should work properly

**Comment by Cats987** [comment]
Epic! Hoping you also add some more blocks to be able to be compressed soon :)

**Comment by sa-shiro** [comment]
this should work for now
(extract the archive, github doesnt allow to upload jars)
[Compressed Blocks-forge-1.19.3.zip](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/12032702/Compressed.Blocks-forge-1.19.3.zip)

**Comment by sa-shiro** [comment]
I forgot to mention the reason why the 1.19.4 version doesn't work on 1.19.3:

In 1.19.3 cherry logs etc don't exist yet which causes the game to crash and because of a mapping difference
