### ISSUE TITLE
Incorrect Texture for Raw Copper Blocks

### ISSUE THREAD

**Issue by HalcyonSeas73** [sa-shiro/Minecraft-Compressed-Blocks#38]
**Mod Version**: 1.3.8
**forge Version**: 47.2.1

**Describe the bug**
The texture for Compressed Raw Copper Blocks (and their higher variants) have the wrong texture.

**Screenshots**

![image](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/84727791/bfe938ff-bd8c-4a68-9d75-30024790b301)

**Comment by sa-shiro** [comment]
by adding the forgotten copper blocks i forgot to exclude "raw_***copper_block***" at the data generation so this is just a visual bug.
also the copper blocks miss their weathering texture, i will have to look into it how those blocks optain their texture.

Will be fixed as soon as i have time

**Comment by sa-shiro** [comment]
fixed in https://github.com/sa-shiro/Minecraft-Compressed-Blocks/commit/528c9395420ee2ebdecb7e53605c01b63f85a1f1
