### ISSUE TITLE
Multiple crafting recipes broken

### ISSUE THREAD

**Issue by Mrsuperx13** [sa-shiro/Minecraft-Compressed-Blocks#4]
**Mod Version**
compressedblocks-1.15.2-2.3.1.jar
**forge Version**
31.1.25

**Describe the bug**
Compressed cobblestone has no recipe to uncompress
Compressed stone has no recipe
(there may be others broken but I havn't managed to check others.)

**How did it happen?**
What did you do that the bug / error / crash happened?

**Screenshots**

**Comment by sa-shiro** [comment]
Uhm again a recipe error and i thought i checked all if they are working haha :D
ill have a look at it again tomorrow

**Comment by sa-shiro** [comment]
```
Compressed Stone: all present
Compressed Cobblestone: missing
```

this time every single recipe has been tested and all are working.

Here's a list of the Compression Levels:
```
Diamond Block: 1
Stone: 3
Granite: 6
Diorite: 6
Andesite: 6
Dirt: 10
Cobblestone: 10
Sand: 10
Red Sand: 4
Gravel: 3
Netherrack: 10
Soul Sand: 3
Redstone Block: 3
```

pusing the update soon
