### ISSUE TITLE
Feature request: RFTools Dimensions compatibility

### ISSUE THREAD

**Issue by H4ckerxx44** [sa-shiro/Minecraft-Compressed-Blocks#40]
Currently, the mod does not support being used in the RFTools Dimensions mod as seen here:
![grafik](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/56711385/bad45e18-90c4-43fb-aa71-565baf5c4e15)

I think it would be pretty cool if the mod would get compatiblity with that, the dimlet upkeep cost can very well be astronomically high (especially for higher-compressed things)

Would love to hear what you think of that.

**Comment by H4ckerxx44** [comment]
Note: More of a feature request instead of a bug report, the only template there is is bug report so I chose that.

**Comment by sa-shiro** [comment]
Sorry for the late response, I am not familiar with RFTools and i dont know how commonly used RFTools is in combination with my mod so currently I do not plan to add support for it, **however** ill try to look into it when i have time.

I am very busy atm and still need to add some missing blocks and update all 1.20 versions inclduing 1.20.4 and 1.20.5

**Comment by H4ckerxx44** [comment]
Appreciate the response!
