### ISSUE TITLE
CB overwrites treasure maps

### ISSUE THREAD

**Issue by RedSnt** [sa-shiro/Minecraft-Compressed-Blocks#42]
**Mod Version**: 1.5.1
**forge Version**: NF: 47.1.105
**Minecraft Version**: 1.20.1

**Describe the bug**
With mod installed, found treasure maps are blank, like replaced by empty regular maps, and "reading" them works like regular maps and just maps the region.

**How did it happen?**
Mod works as intended, it just overwrites treasure maps, perhaps some ID conflict as maps are compressable?

**Comment by sa-shiro** [comment]
Can you provide more details?
Installed Mods, Minecraft Version etc.

**Comment by RedSnt** [comment]
Just tried picking up a treasure map without the mod activated, and it works as intended. When I then enable the mod again, the map remains a treasure map, so it doesn't happen after the treasure map has generated correctly.  

Here's a list of the installed mods, it's a custom minimal one I put together myself, mostly quality of life stuff. Minecraft version is 1.20.1

![image](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/6242718/ccaa23bc-e572-4a65-a0a3-30cd88bb2c88)

**Comment by sa-shiro** [comment]
![Screenshot 2024-05-30 000258](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/7215049/0de5703c-285b-4bfc-8bd5-8f851d2ba27e)

I am unable to reproduce your issue

**Comment by sa-shiro** [comment]
1.20.1, ill have a look

**Comment by sa-shiro** [comment]
Wait, you are using 1.5.1 right?
The latest version for 1.20.1 is 1.5.0 so its likely due to version issues

**Comment by sa-shiro** [comment]
apparently the 1.5.0 neoforge version will not work on 1.20.1, i have to look into it tomorrow
and i also have to look why for some reason it allows installing 1.5.1 on the unsupported minecraft version 1.20.1/2 at all lol

**Comment by RedSnt** [comment]
I did some more testing, because I had tried another compression mod called "Simplest Compression" by IndEvo Studio, and I'm wondering if having that enabled, generating the part of the world where map is, then disabling it and replacing it with Compressed Blocks causes it. Because I just replicated it, still not sure if that's the correct procedure, going to double check.  

And yes, I just used Prism Launcher downloader using Modrinth as the dl source.

**Comment by sa-shiro** [comment]
ah okay
That 1.5.1 does not crash is really questionable as 1.5.1 is intended for 1.20.5+ and because the code base changed a lot, it should be incompatible and crash on game start

**Comment by RedSnt** [comment]
Very odd.. It's funny, because my experience with this modlist has otherwise been completely stable, it's not crashing, just this one weird quirk.   
Going to try and remake my little custom modpack in a newer version. Only reason I went with sub-1.20.5 is because I don't have newest version of java yet.  

Closing this because of version mismatch.

**Comment by sa-shiro** [comment]
> Very odd.. It's funny, because my experience with this modlist has otherwise been completely stable, it's not crashing, just this one weird quirk. Going to try and remake my little custom modpack in a newer version. Only reason I went with sub-1.20.5 is because I don't have newest version of java yet.
> 
> Closing this because of version mismatch.

no need to go straight for 1.20.4 onwards, however id recommend at least 1.20.2, most of your mods should definitely work on 1.20.2, maybe even on 1.20.4 (java 21 is only required starting from 1.20.5)
