### ISSUE TITLE
Compressed ice interferes with natural ice-packed ice-blue ice recipe

### ISSUE THREAD

**Issue by Xeddius** [sa-shiro/Minecraft-Compressed-Blocks#43]
1.20.1
The recipe for compressed ice is conflicting with the recipe to make packed ice and blue ice.
Is there a way to edit a config to disable this recipe or alter it?

**Comment by sa-shiro** [comment]
Oh, i totally forgot about this one 
The current solution is to use a mod that handles duplicate recipes until I fixed it 

You can manually remove all ice recipes within the jar as another option

**Comment by Xeddius** [comment]
An alternative recipe could be 4x ice blocks, while the compression isn't as high, it'll still let you compress it, or alternatively a recipe for just blue ice with recipes to un-craft blue into packed and packed into regular, etc.

4x recipe could be:

```
##.
##.
...
```
With . being empty space
