### ISSUE TITLE
Incorrect Advancement Trigger

### ISSUE THREAD

**Issue by ThreadWeaaver** [sa-shiro/Minecraft-Compressed-Blocks#44]
CB Version: 1.5.1
Fabric Version: 1.20.6

**Describe the bug**
Advancements are triggered incorrectly

**How did it happen?**
I loaded a new world with CB installed, and upon breaking a single oak log, got all CB advancements and 137 levels

With testing it seems that the advancements are being triggered by obtaining any item

**Screenshots**
![2024-06-07_18 33 21](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/168317483/8b3d8918-3104-480b-bd2a-c3fd0abf2b0a)
![2024-06-07_18 33 24](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/168317483/23c42414-1526-409b-928e-e9180a794f58)
![2024-06-07_18 33 31](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/168317483/3d3635d2-1609-4ed1-b7af-d880f165edb5)
![2024-06-07_18 33 37](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/168317483/416e63bd-a450-4e76-a762-6ea405c7ebcc)
![2024-06-07_18 33 43](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/168317483/6cb98532-5701-4c39-aa57-fdbc2342c3a6)
![2024-06-07_18 33 53](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/168317483/1ece33d5-f09d-41cb-937c-626f9f4b86f3)
![2024-06-07_18 33 55](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/assets/168317483/4e506f64-4e3c-42c3-83b8-b4be1df028d7)

**Comment by sa-shiro** [comment]
This should not happen as the advancements check for the exact item upon item pickup
What other mods are u using?

**Comment by ThreadWeaaver** [comment]
Originally I was, but then I loaded a test mod pack  to verify it wasn't a bad combination.

[Here ](https://mclo.gs/h3xUhAz)is the log from loading minecraft, creating a new world, mining a tree, getting the advancements, and exiting:


and here is the mod pack:
[Compressed to the test 1.0.0.zip](https://github.com/user-attachments/files/15750367/Compressed.to.the.test.1.0.0.zip)

**Comment by sa-shiro** [comment]
i see what the issue is, in 1.20.5+ they removed the tag option for advancements which is needed for the advancements to work as intended
