### ISSUE TITLE
Compressed Stone Recipe Broken

### ISSUE THREAD

**Issue by Wiccat** [sa-shiro/Minecraft-Compressed-Blocks#5]
Version 1.15.2-2.4.3:
Compressed Stone recipe in data/compressedblocks/recipes/compressed_stone_s.json is a duplicate of data/compressedblocks/recipes/double_compressed_stone_s.json and prevents compressed stone from being created or showing up in JEI.
Fixed as follows
```json
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "AAA",
    "AAA",
    "AAA"
  ],
  "key": {
    "A": {
      "item": "minecraft:stone"
    }
  },
  "result": {
    "item": "compressedblocks:compressed_stone"
  }
}
```

Edit: Wrapped code in json code formatting

**Comment by sa-shiro** [comment]
too many files to keep an eye open for everything :D
But with the next update that's coming soon, that process has been automated so there won't be any errors
