### ISSUE TITLE
No recepies for the Compressed Blocks.

### ISSUE THREAD

**Issue by smallerYeet** [sa-shiro/Minecraft-Compressed-Blocks#6]
Basically what the Title says. I'm able to craft all the compressed blocks that are added but I'm not able to craft the very first compressed block to start compressing.

Here is a screenshot. https://imgur.com/a/6xji4zZ

I use Forge 34.1.42 and the mod version 5.0.1 in Minecraft 1.16.3
This mod is on a Server if that is Important.

**Comment by sa-shiro** [comment]
im looking into it and fix it fast, i imagine my script didnt generate level 0 compressions xD

**Comment by sa-shiro** [comment]
clsoed in:
https://github.com/sa-shiro/Minecraft-Compressed-Blocks/commit/392f4ec1f4a3037d5dc621d41ab3cda591751729
