### ISSUE TITLE
"CB: Compressed Blocks (compressedblocks) has failed to load correctly" with like 105 mods

### ISSUE THREAD

**Issue by SethFLN** [sa-shiro/Minecraft-Compressed-Blocks#7]
[crash-2021-04-22_23.48.43-fml.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/6362826/crash-2021-04-22_23.48.43-fml.txt)
I tried using the recent one (5.0.6) but figured maybe it had a weird error so I tried 5.0.5 and it still had this error.
It's probably not your fault, but i figured you would want this crash report anyways... maybe...

Also this is the first issue ive posted on github so im very sorry if I did it wrong lol
This mod is perfect for what I need it for and it's a shame i can't use it rn :(

actually 5.0.4 works in my pack so I'll use that for now!

**Comment by sa-shiro** [comment]
## 5.0.6 (latest)
this should work with mekanism, because i removed the compression variants for it
## 5.0.5
Errors because there is something wrong with the config (it maybe doesnt write/find the mekanism blocks

as they are disabled with the latest update, there is no need to fix this issue.

However if you wish to have mekanism compression blocks back, just let me know!

**Comment by SethFLN** [comment]
so 5.0.6 should work with mekanism? it didn't, here's the log from earlier
[crash-2021-04-22_23.45.15-fml.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/6363132/crash-2021-04-22_23.45.15-fml.txt)

Here the log, i figured the error was the same for both versions so I didn't post it in my original post

**Comment by sa-shiro** [comment]
> so 5.0.6 should work with mekanism? it didn't work in my pack, here's the log from earlier
> [crash-2021-04-22_23.45.15-fml.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/6363132/crash-2021-04-22_23.45.15-fml.txt)
> 
> Here the log, i figured the error was the same for both versions so I didn't post it in my original post

Strange, it somehow uses one of my dev workspace paths for the config, but with the 5.0.7 update it should definetly work!
i just uploaded it to curseforge (i tested it by myself)

**Comment by SethFLN** [comment]
client works fine but the server im running crashes on startup, here's the log
[crash-2021-04-23_06.36.14-fml.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/6363256/crash-2021-04-23_06.36.14-fml.txt)

**Comment by sa-shiro** [comment]
> client works fine but the server im running crashes on startup, here's the log
> [crash-2021-04-23_06.36.14-fml.txt](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/6363256/crash-2021-04-23_06.36.14-fml.txt)

can you confirm the version 5.0.7 is working? it does so on my end at least
for now i removed 5.0.5 onwards on curse

[[1.16]compressedblocks-5.0.7.zip](https://github.com/sa-shiro/Minecraft-Compressed-Blocks/files/6363322/1.16.compressedblocks-5.0.7.zip)

**Comment by SethFLN** [comment]
I tried 5.0.7 on the server 3 times before posting :(
5.0.4 works on the server just fine

**Comment by sa-shiro** [comment]
> I tried 5.0.7 on the server 3 times before posting :(
> 5.0.4 works on the server just fine

yeah i am already working on it and it works fine so far (on server)
the issue is that it cant find the path on server, because the mod gets its path from the Minecraft Game Instance and this doesnt exist on dedicated server

Im running some initial tests before uploading the final working version (finally ^^)

**Comment by sa-shiro** [comment]
> I tried 5.0.7 on the server 3 times before posting :(
> 5.0.4 works on the server just fine

i removed the config for now (i need to figure out a working way for both, server and client) and it should work now as tested several times
