### ISSUE TITLE
flint, rotten flesh, and gunpowder block are not craftable

### ISSUE THREAD

**Issue by Stielharn** [sa-shiro/Minecraft-Compressed-Blocks#8]
i cant craft my flint, rotten flesh or gunpowder into blocks
![2021-04-25_19 57 50](https://user-images.githubusercontent.com/69947026/116013897-93835280-a600-11eb-8a2b-a9623ddfca3e.png)

**Comment by sa-shiro** [comment]
Oh I totally forgot about them!! 

The data generator generates everything now, but those blocks have a custom recipe so it can't be generated by the data generator, I'll add them back tomorrow as fast as possible!
Thanks for posting this issue

**Comment by Stielharn** [comment]
> Oh I totally forgot about them!!
> 
> The data generator generates everything now, but those blocks have a custom recipe so it can't be generated by the data generator, I'll add them back tomorrow as fast as possible!
> Thanks for posting this issue

Thank you for seeing this and responding so fast im excited to super compact my flint

**Comment by sa-shiro** [comment]
Just let this open as long as this isn't fixed 😅
Sadly I'm not home so can't fix it right away, but tomorrow at about 8am CEST it will be fixed ^^

**Comment by Stielharn** [comment]
ok ty
