### ISSUE TITLE
all compressed versions of blocks show up as 3.48 billion blocks

### ISSUE THREAD

**Issue by Stielharn** [sa-shiro/Minecraft-Compressed-Blocks#9]
**Mod Version**
5.0.12
**forge Version**
36.1.13

**Describe the bug**
All compressed verions of blocks are showing 3.48.. billion blocks instead of the actual count

**How did it happen?**
Nothing i remember doing just noticed it

**Screenshots**
![Base Profile Screenshot 2021 05 17 - 15 23 26 26](https://user-images.githubusercontent.com/69947026/118545202-49375200-b724-11eb-98c5-d60ec334aa78.png)

**Comment by sa-shiro** [comment]
oh well thats weird, ill fix it soon!
